# Generated by Django 4.2.30 on 2026-05-03 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expeditions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expeditionmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expedition',
            name='chief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_expeditions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='expeditionmember',
            unique_together={('expedition', 'user')},
        ),
    ]
